CREATE TABLE DEPARTMENT
(
DEPARTMENT_NAME VARCHAR(90) PRIMARY KEY,
DEPARTMENT_LEADER_NAME VARCHAR(64),
NUMBER_OF_EMPLOYEES INTEGER,
CONSTRAINT AK1 UNIQUE (DEPARTMENT_LEADER_NAME)
);

CREATE TABLE ACCESS_RIGHTS
(
RIGHT_ID INTEGER PRIMARY KEY,
RIGHT_NAME VARCHAR(32),
CONSTRAINT AK4 UNIQUE (RIGHT_NAME)
);

CREATE TABLE STAFFING_TABLE
(
POST VARCHAR(100) PRIMARY KEY,
SALARY INTEGER,
RIGHT_ID INTEGER,
CHECK (SALARY>0),
FOREIGN KEY (RIGHT_ID) REFERENCES ACCESS_RIGHTS(RIGHT_ID)
);

CREATE TABLE EMPLOYEE
(
EMPLOYEE_ID INTEGER PRIMARY KEY,
CHECK (EMPLOYEE_ID>0),
EMPLOYEE_NAME VARCHAR(64),
BIRTH DATE,
EMAIL VARCHAR(100),
CHECK(EMAIL LIKE '%@company.ru'),
PASSWORD VARCHAR(100),
POST VARCHAR(100),
DEPARTMENT_NAME VARCHAR(90),
DATE_OF_EMPLOYMENT DATE,
FOREIGN KEY (DEPARTMENT_NAME) REFERENCES DEPARTMENT(DEPARTMENT_NAME),
FOREIGN KEY (POST) REFERENCES STAFFING_TABLE(POST),
CONSTRAINT AK2 UNIQUE (EMAIL,PASSWORD)
);

CREATE TABLE PROJECT
(
PROJECT_ID INTEGER PRIMARY KEY,
PROJECT_NAME VARCHAR(100),
START_PROJECT DATE,
END_PROJECT DATE,
PROJECT_STATUS VARCHAR(32),
CONSTRAINT AK3 UNIQUE (PROJECT_NAME,START_PROJECT,END_PROJECT)
);

CREATE TABLE PARTICIPATION
(
EMPLOYEE_ID INTEGER,
PROJECT_ID INTEGER,
PRIMARY KEY (EMPLOYEE_ID,PROJECT_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID)
);